# -*- coding: utf-8 -*-
"""TA_DataCleaning.ipynb

Automatically generated by Colaboratory.

"""

import os
import pandas as pd
os.listdir()

path='drive/My Drive/Text Analytics/Dataset/'

cd drive/My Drive/Text Analytics/Dataset/

test = pd.read_csv('yelp_review.csv')

test.head(10)

test.shape

del test['review_id']
del test['user_id']
del test['business_id']
del test['funny']
del test['cool']

pos_test = test['stars']>=4
pos_test = test[pos_test]
neg_test = test['stars']<=2
neg_test = test[neg_test]
avg_test = test['stars']==3
avg_test = test[avg_test]

print(pos_test.shape)
print(neg_test.shape)
print(avg_test.shape)

new_pos_df = pos_test.sample(25000)
new_neg_df = neg_test.sample(25000)
new_avg_df = avg_test.sample(25000)

print(new_pos_df.isnull().values.any())
print(new_neg_df.isnull().values.any())
print(new_avg_df.isnull().values.any())

index=list(range(1,25001))

len(index)

new_pos_df.index = index
new_neg_df.index = index
new_avg_df.index = index

new_pos_df.to_csv('pos_cleaned_25k_yelp.csv',index=False)
new_neg_df.to_csv('neg_cleaned_25k_yelp.csv',index=False)
new_avg_df.to_csv('avg_cleaned_25k_yelp.csv',index=False)

print(new_pos_df.shape)
print(new_neg_df.shape)
print(new_avg_df.shape)

new_pos_df.head(10)

new_neg_df.head(10)

new_avg_df.head(10)